server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-container:8761/eureka
  instance:
    hostname: eureka-container

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: BackWeb
          uri: lb://BackWeb
          predicates:
            - Path=/api/v0/**
        - id: BackEmpresa
          uri: lb://BackEmpresa
          predicates:
            - Path=/api/v0-empresa/**

